FROM node:16.15.0 as build-stage
WORKDIR /var/jenkins_home/workspace/deploytest/testproject_react
COPY package*.json ./
RUN npm install
COPY . .
RUN npm run build
FROM nginx:stable-alpine as production-stage
# RUN apk update && apk add certbot

COPY --from=build-stage /var/jenkins_home/workspace/deploytest/testproject_react/build /usr/share/nginx/html
COPY --from=build-stage /var/jenkins_home/workspace/deploytest/testproject_react/deploy_conf/nginx.conf /etc/nginx/conf.d/default.conf
# RUN mkdir /etc/nginx/ssl
COPY ./fullchain2.pem /etc/nginx/ssl/
COPY ./privkey2.pem /etc/nginx/ssl/
EXPOSE 80
EXPOSE 443
CMD ["nginx", "-g","daemon off;"]